### ISSUE TITLE
Documentation on how component dependencies are handled

### ISSUE THREAD

**Issue by metasoarous** [danielsz/system#24]
It's not clear from the documentation how component dependencies are handled. For example, If you have a db connection component, it's not clear how you'd access that connection from a route handler. 

Would you mind adding some details to the README, and making the `example`s a bit more robust to further illustrate (e.g. adding a db component and a single `POST` route called from the front end)?

**Comment by danielsz** [comment]
Hi, 

Thank you for the feedback. Let's see how we can best remediate this.

I think you'll understand how to access components with this: https://github.com/danielsz/system#at-runtime

Does that clear the confusion?

The problem with adding a db component in the example is that we can't make the assumption that the user actually has a database installed. Suggestions welcome.

**Comment by metasoarous** [comment]
Right; I read that section, and saw that one could therefor access the component they need by digging into the global system var. I just wanted clarity as to whether this is the _only_ way, in particular because this is somewhat antithetical to Stuart Sierra's vision of Component, wherein each component should only have access to the components upon which it depends, eschewing direct access of global state. Given this, it would seem prudent to more clearly spell out and highlight this difference.

I see your point with regard to the database issue. It wouldn't actually _have_ to be a database, just some situation where you have code associated with one component, and it accesses the state of another component via the system var. If there's something other than a database that would let you illustrate that, then great. Otherwise, perhaps just add another example dir where you throw in a couple more bells and whistles. Even if folks don't have everything installed on their system, they can still look at it, and run the simpler examples to get the "hands on" part of it.

**Comment by danielsz** [comment]
You're making good points, @metasoarous . 

It is certainly not the *only* way, it's only *one* way. 
Personally, I do not feel there is an ickiness to treat the system var as a read-only global state entity, because this is what it is. However, if you think that that you can bring a purer/cleaner interpretation of Stuart Sierra's vision on the table, I'm all for it. 

I will try to post a more involved example as soon as I have some time, and we'll then be able to discuss and refine the concepts. Does that sound good?

**Comment by metasoarous** [comment]
To be clear, I don't think it's necessarily icky to treat the system var as such either; there are advantages and disadvantages both ways. I don't even know if Stuart Sierra would necessarily think it "icky", but avoiding it was certainly a motivating aspect of his design, hence my conclusion that it's a point worth highlighting.

I'm not sure how you would re-engineer system so as to be more in line with Stuart Sierra's vision of more local/restricted access. If as you say, the global state entity is not the _only_ way with system, perhaps getting a sense of some of the alternatives from you would spark some idea about an alternate interpretation.

Discussing a more involved example or two sounds great; looking forward to that :-)

Thanks

That sounds great. Thanks.

To be clear, I'm not _personally_ saying there is ickiness in treating the system var as a global state entity. For example, om

**Comment by danielsz** [comment]
Hi @metasoarous 

I presume you've seen the [holygrail](https://github.com/danielsz/holygrail) repo, but have you seen [sente-system](https://github.com/danielsz/sente-system)? No database, but websockets galore and cross-components access (in the routes). Definitely more involved.

You wanted to see a CRUD example with some Compojure routes and a REST API, right? The H2 database would fit nicely, since it is a maven dependency and runs in-memory. I can't get myself to write another CRUD example, I'm afraid. Would you like to give it a try? I'll help with any difficulty you might encounter.

**Comment by danielsz** [comment]
An advanced example has been posted. Would you like to review and comment?

Thanks.

**Comment by metasoarous** [comment]
Nice; I hadn't looked too thoroughly, but I saw what I would have wanted to see in there.

I also just submitted a PR for a little addition to the README that would have clarified things for me as well. Let me know if there is anything I should amend there.

**Comment by danielsz** [comment]
Sounds great. 

I can't find your PR, though.

**Comment by metasoarous** [comment]
Woops; forgot to actually hit submit (it's late here...)

**Comment by danielsz** [comment]
Hehe, these thins happen :-)
Thanks!

**Comment by danielsz** [comment]
Hello Christopher, 

I am happy and grateful you've been raising the DI issue. 
I have thought about this, and support for common DI scenarii has landed in the latest snapshot version. Additionally, a new example is available in the examples folder. 
I intend to fully support common DI patterns, so please feel free to review, comment and contribute.

Thank you again!

**Comment by danielsz** [comment]
Closing this for now since support is ongoing.
If there is anything else, please feel free to re-open.
