### ISSUE TITLE
Check that supplied Var is member of project's namespace hierarchy

### ISSUE THREAD

**Issue by martinklepsch** [danielsz/system#91]
Hey again 👋  Two things that took me a while to figure out when setting everything up:

---

**1** The system var passed to the `system` task can't be in `boot.user` otherwise nothing will be reloaded.
 
If this is correct maybe adding an assert that the namespace of the var isn't `boot.user` would be good? Happy to provide a PR if wanted.

---

**2** The `files` option takes filenames and not paths.

Not sure what to do about this, perhaps a warning if the filenames contain slashes? Also a `--paths` option seems reasonable in that context although not super necessary.

--- 

Now that it's all working, wow is it awesome 🚀  🎉

**Comment by danielsz** [comment]
Hi Martin, 

I'm happy you managed to wire it up in the end. 
Thank you for the report on your first impressions, especially the pains you had to overcome. 

You're touching on an important subject, that of the feedback a system gives to its user, or to use other words, the ease with which you can approach and master it. 

There are many things to say, and many possible things to do in order to address the shortcomings. 
The one important guideline for me is that the approach should be principled, not ad-hoc. 

The first principled mechanism to use is the solution that the creators of Boot came up with, that is to say, the auto-documenting feature of Boot tasks. 

Maybe you can look into the way the `files` option is documenting itself, and improve on this with a PR.

Regarding the first point (the `system` var in `boot.user`), first I would like to make sure I understand what happened. Do you have a snippet available so can I look into that?

**Comment by martinklepsch** [comment]
Hey Daniel,

here's a repro of the "system var in `boot.user`" thing: https://github.com/martinklepsch/boot-system-repro, start it with `boot dev-sys` and then change any of the `prn` calls. Code is reloaded but somehow to no effect, i.e. the printed strings remain as they were when starting the `dev-sys` task.

Regarding the files path vs. name thing, the current docstring:
```
A vector of files. Will reset the system if a filename in the supplied vector changes
```
I somehow expected it to be paths since filenames might be ambiguous, that said the docstring is pretty clear that it looks for filenames. Maybe nothing to do here, maybe a `filename (not path)` would have helped me. But then again that's just adding verbosity for a rare case.

I thought checking for slashes might be a good UX improvement without cluttering docs but I definitely see that things like this can quickly explode the size of a codebase.

Let me know if you want a PR for either of these things :)

**Comment by martinklepsch** [comment]
And once again: sub-second system restarting is magic! ✨

**Comment by danielsz** [comment]
Thank you, Martin, I've had a look at the repo. What happens is that the `tools.namespace` tracker is configured to track only the project hierarchy, not outside of it. This way, you can change your system configuration and thanks to the Var's dynamic resolution mechanism, you can restart a system with new definitions/configuration/components. That is the explanation of the design. 

Now how do I catch a case like yours? Well, I could check the Var you're passing in and see if it belongs to the project hierarchy, and if not, throw an error.

I will take  the time to reflect on this, maybe explore other options. No need for a PR for now. Thank you!

Another thing, the latest snapshot version has more options for the `files` vector, including support for  `paths` and `regexes`. That should make you happy, too.

**Comment by danielsz** [comment]
Closing for now. Please feel free to reopen if something is not right.

**Comment by martinklepsch** [comment]
Hi @danielsz, sorry for not replying earlier :) The explanation makes perfect sense of course. I still think this might be a good improvement to help beginners. If you're closing this issue I'd lobby for another issue to track the "Var outside if namespace hierarchy" issue you described above — or we just reopen and rename this one.

**Comment by danielsz** [comment]
:+1:

**Comment by danielsz** [comment]
Can we close this, @martinklepsch?

**Comment by martinklepsch** [comment]
Just saw this now, haven't got a chance to give it a try but I'm sure it's perfect, so sure close this :)
